config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'

  resources :meals
  resources :recipes
  resources :ingredients, only: [ :create, :index, :edit, :update ] do
    collection do
      get :search
      get :minerals
      get :vitamins
    end
    resources :size_conversions, only: [ :index ]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredient_amounts, dependent: :destroy
  accepts_nested_attributes_for :ingredient_amounts
  has_many :ingredients, through: :ingredient_amounts

  Ingredient::NUTRIENTS.keys.each do |nutrient|
    define_method nutrient do
      ingredient_amounts.map(&nutrient).sum / servings
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def new
    @recipe = Recipe.new
    @recipe.ingredient_amounts.build
  end

  def create
    @recipe = Recipe.create(recipe_params)
    render plain: "Recipe created - #{@recipe.name}"
  end

  def index
    @recipes = Recipe.all
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :time, :cooking_time, :instructions, :servings, ingredient_amounts_attributes: [ :ingredient_id, :unit_name, :unit_number ])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form_ingredient.html.erb
<div data-controller="ingredient-list" data-target="recipes.ingredient" data-ingredient-list-parent="recipes">
  <%= form_ingredient.text_field :ingredient_id, 
    list: "ingredients", 
    data: { action: 'change->ingredient-list#replaceId focus->ingredient-list#selectAll', target: 'ingredient-list.name' },
    class: 'ingredient-name',
    required: true,
    placeholder: 'ingredient' %>
  <%= form_ingredient.number_field :unit_number, 
    data: { target: 'ingredient-list.number' },
    step: 0.01,
    required: true %>
  <%= form_ingredient.text_field :unit_name,
    list: "units-#{form_ingredient.index}",
    data: { action: 'focus->ingredient-list#selectAll' },
    required: true,
    placeholder: 'tbsp' %>
  <datalist id="units-<%= form_ingredient.index %>" data-target="ingredient-list.unitList">
  </datalist>
  <button data-action="ingredient-list#removeIngredient">Delete</button>
  <template data-target="ingredient-list.searchTemplate">
    <p data-target="ingredient-list.link">The ingredient "_" is not in the database. To search for it, click <%= link_to 'here', search_ingredients_path(search: '_'), data: { action: 'recipes#searchIngredient' } %>
  </template>
</div>

app/views/recipes/create.html.erb
<div class="snackbar">Created Recipe - "<%= @recipe.name%>"</div>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<%= link_to 'Meal planner', meals_path %>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= recipe.name %> <em>(<%= recipe.servings %> servings)</em>
    <div><strong>Calories</strong> <%= recipe.calories.round %> <strong>Protein</strong> <%= recipe.protein.round %> <strong>Fat</strong> <%= recipe.fat.round %> <strong>Carb</strong> <%= recipe.carb.round %></div>
    </li>
  <% end %>
</ul>
<%= link_to 'Add recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<div data-controller="recipes" class="recipes">
  <div>
    <h1>New Recipe</h1>

    <%= form_with model: @recipe, html: { data: { action: 'ajax:before->recipes#updateForm ajax:success->recipes#handleCreate', target: 'recipes.form' } } do |f| %>

      <div class="recipe-data">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'recipe-name', required: true %>
      </div>
      <div class="recipe-data">
        <%= f.label :time, 'Prep time (min)' %>
        <%= f.number_field :time %>
      </div>
      <div class="recipe-data">
        <%= f.label :cooking_time, 'Cooking time (min)' %>
        <%= f.number_field :cooking_time %>
      </div>
      <div class="recipe-data">
        <%= f.label :servings %>
        <%= f.number_field :servings %>
      </div>

      <div data-target="recipes.ingredientList">
        <h2>Ingredients</h2>
        <%= f.fields_for :ingredient_amounts do |ia| %>
          <%= render partial: 'form_ingredient', object: ia %>
        <% end %>
      </div>
      <datalist id="ingredients" data-target="recipes.ingredientOptions">
        <%= options_for_select Ingredient.all.map{|i| [i.name, i.id, { data: { url: ingredient_size_conversions_path(i) } }]} %>
      </datalist>
      <%= link_to 'Add ingredient', '#', data: { action: 'recipes#addIngredient' }, class: 'search' %>
      <h2>Instructions</h2>
      <%= f.text_area :instructions %>

      <%= button_tag 'Save', class: 'save' %>

      <template data-target="recipes.ingredientAmountTemplate">
        <%= f.fields_for :ingredient_amounts, @recipe.ingredient_amounts.build do |ia| %>
          <%= render partial: 'form_ingredient', object: ia %>
        <% end %>
      </template>
    <% end %>
  </div>
  <div>
    <div data-target="recipes.searchResults" class="searchResults"></div>
  </div>
</div>