config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'

  resources :meals
  resources :recipes
  resources :ingredients, only: [ :create, :index, :edit, :update ] do
    collection do
      get :search
      get :minerals
      get :vitamins
    end
    resources :size_conversions, only: [ :index ]
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :size_conversions, -> { order(gram_equivalent: :desc) }
  belongs_to :serving_size, class_name: "SizeConversion", foreign_key: :size_conversion_id, optional: true
  accepts_nested_attributes_for :size_conversions

  NUTRIENTS = { 
    protein: "Protein",
    fat: "Total lipid (fat)",
    carb: "Carbohydrate, by difference",
    calories: "Energy",
    fiber: "Fiber, total dietary",
    sugar: "Sugars, total",
    calcium: "Calcium, Ca",
    iron: "Iron, Fe",
    magnesium: "Magnesium, Mg",
    phosphorus: "Phosphorus, P",
    potassium: "Potassium, K",
    sodium: "Sodium, Na",
    zinc: "Zinc, Zn",
    vitamin_c: "Vitamin C, total ascorbic acid",
    thiamin: "Thiamin",
    riboflavin: "Riboflavin",
    niacin: "Niacin",
    vitamin_b6: "Vitamin B-6",
    folate: "Folate, DFE",
    vitamin_b12: "Vitamin B-12",
    vitamin_a: "Vitamin A, IU",
    vitamin_e: "Vitamin E (alpha-tocopherol)",
    vitamin_d: "Vitamin D",
    vitamin_k: "Vitamin K (phylloquinone)",
    saturated_fat: "Fatty acids, total saturated",
    monounsaturated_fat: "Fatty acids, total monounsaturated",
    polyunsaturated_fat: "Fatty acids, total polyunsaturated",
    trans_fat: "Fatty acids, total trans",
    cholesterol: "Cholesterol"
  }

  MINERALS = [ :calcium, :iron, :magnesium, :phosphorus, :potassium, :sodium, :zinc  ]
  
  VITAMINS = [ :vitamin_a, :thiamin, :riboflavin, :niacin, :vitamin_b6, :vitamin_b12, :folate, :vitamin_c, :vitamin_d, :vitamin_e, :vitamin_k ]
  
  MACROS = [ :calories, :protein, :fat, :carb ]
  # note the values for all nutrients are per 100g of ingredient
  def self.create_with_sizes(hash)
    params = { name: hash["desc"]["name"], ndbno: hash["desc"]["ndbno"] }
    NUTRIENTS.each do |key, value|
      params[key] = hash["nutrients"].find{|nutrient| nutrient["name"] === value }.try :[], "value"
    end
    instance = create!(params)
    hash["nutrients"][0]["measures"].each do |size|
      instance.size_conversions.create!(unit: size["label"], gram_equivalent: size["eqv"], amount: size["qty"])
      raise if size["eunit"] != "g"
    end
    instance
  end

  def grams_in(unit_name)
    size_conversions.find_by(unit: unit_name).grams
  end

  def serving_size_name
    serving_size ? "#{serving_size.amount} #{serving_size.unit}" : "100g"
  end

  def serving_size_g
    serving_size ? serving_size.gram_equivalent : 100
  end

  def per_serving(nutrient)
    serving_size_g / 100.0 * send(nutrient)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  layout proc {|controller| controller.request.xhr? ? false: "application" }
  protect_from_forgery except: :search

  def index
    @ingredients = Ingredient.includes(:serving_size, :size_conversions).all
  end

  def minerals
    @ingredients = Ingredient.all
  end

  def vitamins
    @ingredients = Ingredient.all
  end

  def edit
    @ingredient = Ingredient.includes(:size_conversions).find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update(ingredient_params)
    redirect_to ingredients_url
  end

  def search
    search_response = NutritionApi.search(params[:search])
    @results = search_response[:items]
    respond_to do |format|
      format.js do
        if @results.nil?
          @ingredient = Ingredient.new
          render template: 'ingredients/new.html.erb'
        else
          render template: 'ingredients/search.html.erb' 
        end
      end
    end
  end

  def create
    search_response = NutritionApi.find(params[:id])
    ingredient_hash = search_response["foods"][0]["food"]
    ingredient = Ingredient.create_with_sizes(ingredient_hash)
    respond_to do |format|
      format.html { redirect_to search_ingredients_url, success: "#{ingredient.name} added" }
      format.json { render json: { name: ingredient.name, id: ingredient.id, conversions: ingredient.size_conversions.pluck(:unit) } }
    end
  end

private

  def ingredient_params
    params.require(:ingredient).permit(:name, :size_conversion_id, size_conversions_attributes: [ :unit, :gram_equivalent, :amount ])
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

  def round(size)
    size.is_a?(String) ? round_string(size) : round_number(size)
  end

  def round_string(size)
    match = size.match(/[0-9.]+/)
    return size unless match
    number = match[0]
    round_number = number_with_precision number, strip_insignificant_zeros: true
    size.sub(number, round_number.to_s)
  end

  def round_number(size)
    number_with_precision size, precision: 1, strip_insignificant_zeros: true
  end
end

app/views/ingredients/edit.html.erb
<h1><%= @ingredient.name %></h1>

<ul>
  <% @ingredient.size_conversions.each do |size| %>
    <li><%= size.amount unless size.amount == 1 %> <%= size.unit %> = <%= size.gram_equivalent %>g</li>
  <% end %>
</ul>

<%= form_with model: @ingredient do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :size_conversion_id, 'Reference Size' %>
    <%= f.select :size_conversion_id, @ingredient.size_conversions.map{|size| [ size.unit, size.id ]} %>
  </div>
  <% if false %>
  <%= f.fields_for :size_conversions, @ingredient.size_conversions.build do |s| %>
    <div>
      <%= s.label :amount %>
      <%= s.number_field :amount %>
    </div>
    <div>
      <%= s.label :unit %>
      <%= s.text_field :unit %>
    </div>
    <div>
      <%= s.label :gram_equivalent %>
      <%= s.number_field :gram_equivalent %>
    </div>
  <% end %>
  <% end %>
  <%= button_tag 'Update' %>
<% end %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<table data-controller="table">
  <thead>
    <tr data-action="click->table#sort">
      <th data-type="name">Name</th>
      <th>Serving Size</th>
      <th data-type="calories">Calories</th>
      <th data-type="fat">Fat</th>
      <th data-type="protein">Protein</th>
      <th data-type="carb">Carb</th>
    </tr>
  </thead>
  <tbody class="list">
  <% @ingredients.each do |ingredient| %>
    <tr>
      <td class="name"><%= link_to ingredient.name, [ :edit, ingredient ] %></td>
      <td><%= round ingredient.serving_size_name %></td>
      <td class="calories"><%= round ingredient.per_serving(:calories) %></td>
      <td class="fat"><%= round ingredient.per_serving(:fat) %></td>
      <td class="protein"><%= round ingredient.per_serving(:protein) %></td>
      <td class="carb"><%= round ingredient.per_serving(:carb) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/ingredients/minerals.html.erb
<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <% Ingredient::MINERALS.each do |mineral| %>
        <th><%= Ingredient::NUTRIENTS[mineral] %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <% Ingredient::MINERALS.each do |mineral| %>
        <td><%= ingredient.send mineral %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/ingredients/new.html.erb
<h2>Not Found</h2>
<p>No ingredient by that name could be found in the USDA database. Please enter the details manually.</p>

<%= form_with model: @ingredient do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <h3>Macros (per 100g)</h3>
  <div>
    <%= f.label :calories %>
    <%= f.number_field :calories %>
  </div>
  <div>
    <%= f.label :protein %>
    <%= f.number_field :protein %>
  </div>
  <div>
    <%= f.label :fat %>
    <%= f.number_field :fat %>
  </div>
  <div>
    <%= f.label :carbs %>
    <%= f.number_field :carbs %>
  </div>

<% end %>

app/views/ingredients/search.html.erb
<h1>Search Results: "<%= params[:search] %>"</h1>
<% if @results %>
  <ul>  
    <% @results.each do |result| %>
      <li title="<%= result['name'] %>">
        <%= truncate result['name'], length: 50 %> <%= button_to 'Add to db', ingredients_path(id: result['ndbno']), remote: true, form: { data: { type: :json, action: 'ajax:success->recipes#handleIngredientCreation' }} %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<ul>
  <% @ingredient.size_conversions.each do |size| %>
    <li><%= size.amount unless size.amount == 1 %> <%= size.unit %> = <%= size.gram_equivalent %>g</li>
  <% end %>
</ul>

app/views/ingredients/vitamins.html.erb
<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <% Ingredient::VITAMINS.each do |vitamin| %>
        <th><%= Ingredient::NUTRIENTS[vitamin] %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <% Ingredient::VITAMINS.each do |vitamin| %>
        <td><%= ingredient.send vitamin %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>